import axios from 'axios'

process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0

export default async () => {
  return await new Promise((resolve) => {
    setTimeout(async () => {
      axios.post('https://localhost:4000/dev/contract/GCNANNNLGDICM5NJOT7QD7MLW34M4WLJPTNOAXWEAR4CE4LO23FZ5WDR/run', {
        to: 'GAWSNOA5AMEXLQ2SJM65RH25CEM7O7OV7ZYBSGSGNFUGBJBCGQRAAHOX',
        source: 'GAWSNOA5AMEXLQ2SJM65RH25CEM7O7OV7ZYBSGSGNFUGBJBCGQRAAHOX',
        amount: '100'
      })

      resolve('AAAAAC0muB0DCXXDUks92J9dERn3fdX+cBkaRmloYKQiNCIAAAAAZAAACZsAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAALAAAAAAAAAAAAAAAAAAAAAA==')
    }, 5000)
  })
}